# This file was generated by GoReleaser. DO NOT EDIT.
class Tb < Formula
  desc ""
  homepage ""
  version "0.0.1"

  if OS.mac?
    url "https://github.com/TouchBistro/tb/releases/download/v0.0.1/tb_0.0.1_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "f11f0993f871cb93fcbae5c1b8afb8c4113fbeef1cec77adaeda7c0ef4056194"
  elsif OS.linux?
  end

  def install
    bin.install "program"
  end

  test do
    system "#{bin}/program --version"
  end
end
