# This file was generated by GoReleaser. DO NOT EDIT.
class Tb < Formula
  desc "a CLI for running services on a development machine"
  homepage ""
  version "3.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/TouchBistro/tb/releases/download/3.3.0/tb_3.3.0_Darwin_x86_64.tar.gz"
    sha256 "23879256d65ef0b38b3eb6520dc320a5ee084fa2b5e88578d9c812b3d7834185"
  elsif OS.linux?
    url "https://github.com/TouchBistro/tb/releases/download/3.3.0/tb_3.3.0_Linux_x86_64.tar.gz"
    sha256 "8dbfdbebfc68a21aecbdb10bb32be0c7abf1b2a4366011c337d33b69bcb2d72b"
  end

  def install
    bin.install "tb"
    bash_completion.install "dist/tb.bash"
    zsh_completion.install "dist/_tb"
    man1.install Dir["dist/man1/*.1"]
  end

  test do
    system "#{bin}/tb --version"
  end
end
